// icons.js
import {
  FaBuilding,
  FaCity,
  FaHospital,
  FaHome,
  FaIndustry,
  FaLandmark,
  FaUniversity,
  FaWarehouse,
  FaStore,
  FaHotel,
  FaSchool,
  FaChurch,
  FaMosque,
  FaSynagogue,
  FaGavel,
  FaArchway,
  FaPlaceOfWorship,
  FaClinicMedical,
  FaMonument,
} from "react-icons/fa";

export const Icons = {
  Building: FaBuilding,
  City: FaCity,
  Hospital: FaHospital,
  Home: FaHome,
  Industry: FaIndustry,
  Landmark: FaLandmark,
  University: FaUniversity,
  Warehouse: FaWarehouse,
  Store: FaStore,
  Hotel: FaHotel,
  School: FaSchool,
  Church: FaChurch,
  Mosque: FaMosque,
  Synagogue: FaSynagogue,
  Court: FaGavel,
  Archway: FaArchway,
  PlaceOfWorship: FaPlaceOfWorship,
  Clinic: FaClinicMedical,
  Monument: FaMonument,
};

export default Icons;
