const companiesData = [
  {
    companyName: "Example Company 1",
    billingAddress: {
      Street: "123 Main Street",
      City: "City1",
      State: "State1",
      BillingCode: "BillingCode1",
      PostalCode: "12345",
    },
    shippingAddress: {
      Street: "456 Shipping Street",
      City: "City2",
      ShippingCode: "ShippingCode1",
      PostalCode: "54321",
    },
    owner: "user_id_1",
    description: "Description of Example Company 1",
    rating: "Active",
    website: "https://example.com",
    tickerSymbol: "SYM1",
    companyType: "Customer",
    ownership: "Private",
    industry: "Technology",
    employees: 100,
    annualRevenue: 1000000,
    tag: "Tag1",
    createdBy: "user_id_1",
    modifiedBy: "user_id_2",
    lastActivityTime: new Date(),
    recordId: 1,
  },
  {
    companyName: "Example Company 2",
    billingAddress: {
      Street: "789 Main Street",
      City: "City3",
      State: "State2",
      BillingCode: "BillingCode2",
      PostalCode: "54321",
    },
    shippingAddress: {
      Street: "012 Shipping Street",
      City: "City4",
      ShippingCode: "ShippingCode2",
      PostalCode: "98765",
    },
    owner: "user_id_2",
    description: "Description of Example Company 2",
    rating: "Acquired",
    website: "https://example2.com",
    tickerSymbol: "SYM2",
    companyType: "Partner",
    ownership: "Public",
    industry: "Finance",
    employees: 200,
    annualRevenue: 2000000,
    tag: "Tag2",
    createdBy: "user_id_2",
    modifiedBy: "user_id_1",
    lastActivityTime: new Date(),
    recordId: 2,
  },
  {
    companyName: "Example Company 3",
    billingAddress: {
      Street: "345 Main Street",
      City: "City5",
      State: "State3",
      BillingCode: "BillingCode3",
      PostalCode: "13579",
    },
    shippingAddress: {
      Street: "678 Shipping Street",
      City: "City6",
      ShippingCode: "ShippingCode3",
      PostalCode: "97531",
    },
    owner: "user_id_3",
    description: "Description of Example Company 3",
    rating: "Market Failed",
    website: "https://example3.com",
    tickerSymbol: "SYM3",
    companyType: "Vendor",
    ownership: "Government",
    industry: "Education",
    employees: 50,
    annualRevenue: 500000,
    tag: "Tag3",
    createdBy: "user_id_3",
    modifiedBy: "user_id_3",
    lastActivityTime: new Date(),
    recordId: 5,
  },
];

export default companiesData;
