const user = {
  firstName: "John",
  lastName: "Doe",
  email: "john@example.com",
  phone: "+1234567890",
  address: {
    street: "123 Main St",
    city: "Anytown",
    state: "CA",
    country: "USA",
    zipCode: "12345",
  },
  username: "johndoe",
  dateOfBirth: "1990-01-01",
  website: "https://www.example.com",
  avatar: "https://www.example.com/avatar.jpg",
  language: "English",
  countryLocale: "US",
  timeZone: "America/Los_Angeles",
  dateFormat: "MM/DD/YYYY",
  timeFormat: "12-hour",
  role: "user",
  addedBy: "admin",
  modifiedBy: "admin",
  isActive: true,
  verified: true,
  alias: "JD",
  grouping: "Group 1",
  sortOrder: "ascending",
  confirm: true,
  notes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
};

export default user;
